  Q1

In [ ]:
from scipy import stats
import pandas as pd
import scipy
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving Cutlets.csv to Cutlets.csv


In [ ]:
data=pd.read_csv('Cutlets.csv')

In [ ]:
UnitA=pd.Series(data.iloc[:,0])
UnitA

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [ ]:
UnitB=pd.Series(data.iloc[:,1])
UnitB

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [ ]:
# null hypothesis = diameters of both the units are same
# alternate hypothesis = there is a difference in  diameter between the 2 units
# since there are 2 samples and it is a comparison between the 2 units,we use 2 sample 2 tail t test

In [ ]:
p_value=stats.ttest_ind(UnitA,UnitB)

In [ ]:
p_value

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [ ]:
p_value[1]

0.4722394724599501

In [ ]:
# since the alpha value is 0.05,and the p value is 0.47,we fail to reject the null hypothesis,meaning there is no difference between the 2 samples

Q2

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving LabTAT.csv to LabTAT.csv


In [ ]:
data=pd.read_csv('LabTAT.csv')

In [ ]:
stats.f_oneway(data.iloc[:,0],data.iloc[:,1],data.iloc[:,2],data.iloc[:,3])

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [ ]:
# alpha value = o.05, p value = 2.11. Hence there is a difference in TAT of laboratories

Q3

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving BuyerRatio.csv to BuyerRatio (2).csv


In [ ]:
data=pd.read_csv('BuyerRatio.csv')

In [ ]:
x=np.array([[50,142,131,70],[550,351,480,350]])
x

array([[ 50, 142, 131,  70],
       [550, 351, 480, 350]])

In [ ]:
from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [ ]:
stat, p_value, dof, expected = chi2_contingency(x)
stat, p_value, dof, expected

(80.27295426602495,
 2.682172557281901e-17,
 3,
 array([[111.01694915,  91.21892655, 113.05225989,  77.71186441],
        [488.98305085, 401.78107345, 497.94774011, 342.28813559]]))

In [ ]:
p_value

2.682172557281901e-17

In [ ]:
# alpha value = 0.05, p value = 2.68.Hence male-female buter ratio is similar across regions

Q4

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving Costomer+OrderForm.csv to Costomer+OrderForm (2).csv


In [ ]:
data=pd.read_csv('Costomer+OrderForm.csv')
data

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [ ]:
(data['Phillippines'].value_counts,data['Indonesia'].value_counts,data['Malta'].value_counts,data['India'].value_counts)

(<bound method IndexOpsMixin.value_counts of 0      Error Free
 1      Error Free
 2      Error Free
 3      Error Free
 4      Error Free
           ...    
 295    Error Free
 296    Error Free
 297    Error Free
 298    Error Free
 299    Error Free
 Name: Phillippines, Length: 300, dtype: object>,
 <bound method IndexOpsMixin.value_counts of 0      Error Free
 1      Error Free
 2       Defective
 3      Error Free
 4      Error Free
           ...    
 295    Error Free
 296    Error Free
 297    Error Free
 298    Error Free
 299     Defective
 Name: Indonesia, Length: 300, dtype: object>,
 <bound method IndexOpsMixin.value_counts of 0       Defective
 1      Error Free
 2       Defective
 3      Error Free
 4       Defective
           ...    
 295    Error Free
 296    Error Free
 297     Defective
 298    Error Free
 299     Defective
 Name: Malta, Length: 300, dtype: object>,
 <bound method IndexOpsMixin.value_counts of 0      Error Free
 1       Defective
 2      Error Free


In [ ]:
x=np.array([[271,267,269,280],[29,33,31,20]])
x

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [ ]:
from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [ ]:
stat, p_value, dof, expected = chi2_contingency(x)
stat, p_value, dof, expected

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [ ]:
# degree of freedom = 3,alpha value = 0.05

In [ ]:
p_value

0.2771020991233135

In [ ]:
# since the p value is less than the alpha value,we accept he null hypothesis.So the defective % does not vary by the centre